### ISSUE TITLE
CacheControl option based on filetype

### ISSUE THREAD

**Issue by nicekiwi** [adamjarret/s3-publish#6]
This module is fantastic btw! 👍 

Can you add an option to define CacheControl headers based the filetype or regex in the config file. 

Like if I was HTML files to have "CacheControl: max-age=900" and everything else to have "CacheControl: max-age=777600000". <3

**Comment by adamjarret** [comment]
Rules are applied in order, so something like this would work:

    rules: [{
        putParams: (file, params, callback) => callback(null, Object.assign(params, {CacheControl: 'max-age=777600001'}))
    }, {
        pattern: /\.html$/,
        putParams: (file, params, callback) => callback(null, Object.assign(params, {CacheControl: 'max-age=901'}))
    }]

In your case, it could even be simplified:

    rules: [{
        putParams: (file, params, callback) => callback(null, Object.assign(params, {
            CacheControl: file.Key.match(/\.html$/) ? 'max-age=900' : 'max-age=777600000'
        }))
    }]

Glad you like the module!
